version: '3'
services:
  db:
    container_name: "${PROJECT_NAME}_db"
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: $DB_NAME
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
  drupal:
    container_name: "${PROJECT_NAME}_drupal"
    depends_on:
      - db
    build: .
    ports:
      - "80:80"
    volumes:
      - ./app:/app
    restart: always
volumes:
  db_data: